[project]
name = "smart_replenishment"
authors = [
    { name = "analyze inventory levels, consumption patterns, and supplier information to automatically generate purchase", email = "omarsalama102@gmail.com"}
]
description = "a Smart Replenishment Module for a pharmacy supply chain platform. This module should"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
